### ISSUE TITLE
Make error in branch work/louis/routing

### ISSUE THREAD

**Issue by JetseVerschuren** [meshnet/Documentation#11]
I just pulled the last changes from work/louis/routing and i get this error:
```
jetse@GigaPc:~/meshnet/Documentation/protocols$  make
groff -c -ms -Kutf8 -Tutf8 -R src/N2NP.nroff > N2NP.term
groff: couldn't exec refer: No such file or directory
troff: fatal error: can't find macro file s
Makefile:6: recipe for target 'utf8' failed
make: *** [utf8] Error 5
```

**Comment by 0x5c** [comment]
@Ne02ptzero 
```
troff: fatal error: can't find macro file s
```
It needs to be `-mms`. 
In reference to the discussion in slack: if the `man` macro is for `man` pages, it would be stupid to call it `an`.

**Comment by 0x5c** [comment]
@JetseVerschuren can-you try to re-install groff using your distro's package manager?

And just for information purposes: what distro are-you using?

**Comment by 0x5c** [comment]
The `troff: fatal error: can't find macro file s` error should be fixed in branch [0x5c/n2np](https://github.com/meshnet/Documentation/tree/0x5c/n2np).

**Comment by JetseVerschuren** [comment]
I am using Ubuntu 17.10

**Comment by 0x5c** [comment]
And did you reinstall `groff`? It should fix the `groff: couldn't exec refer: No such file or directory` error.
The dependency `refer` does not seem to be included in the ubuntu install.

**Comment by JetseVerschuren** [comment]
For some reson i could execute groff but apt said it wasn't installed. So i just install groff and it worked.

**Comment by 0x5c** [comment]
Seems to be standard behaviour in Ubuntu.
I experienced it in `Ubuntu 16.04` inside Windows' WSL.

Does it work normally if you try to build from `0x5c/n2np`?

**Comment by JetseVerschuren** [comment]
After installing groff using apt both branches work

**Comment by 0x5c** [comment]
Is the `.term` output paginated in both branches?
Also, is the `troff: fatal error: can't find macro file s` error resolved in both?

**Comment by JetseVerschuren** [comment]
The errors are fixed in both branches i'll check for the .term

**Comment by JetseVerschuren** [comment]
Indentation also works on both

**Comment by 0x5c** [comment]
Are headers and footers present on both?

**Comment by JetseVerschuren** [comment]
Yes they are present and both are the same

**Comment by 0x5c** [comment]
Ok, so I'll close this issue.
@Ne02ptzero we need to investigate
