### ISSUE TITLE
Add checks for groff's presence

### ISSUE THREAD

**Issue by 0x5c** [meshnet/Documentation#12]
The make process will halt if the `refer` command and the `s`/`ms` macro are not present, which seems to be a common behaviour in Ubuntu installs (per #11).

The presence of the command `refer` seems to be a good indicator of a complete installation.

The problem seems to be solved as soon as the user installs `groff` with the distro's package manager.

**Comment by 0x5c** [comment]
To clarify: the `groff` command is present in fresh Ubuntu installs, but in an incomplete manner.

**Comment by Ne02ptzero** [comment]
Instead of looking for the `refer` binary, I think we should look for the `/usr/share/groff/1.22.3/tmac/s.tmac` file, in order to check if the `-ms` option is usable. The only problem is to determine somehow the groff version on the builder's system.

**Comment by JetseVerschuren** [comment]
You could check for `/usr/share/groff/*/tmac/s.tmac`

**Comment by 0x5c** [comment]
The problem with checking the `s.tmac` is that it is dependent on a specific install path, which is not always the case. Running `which refer` will work with any installation.

**Comment by 0x5c** [comment]
#13 should avoid this issue resurfacing later.
