### ISSUE TITLE
Broadcasts as defined in the current master will break on 19th of January 2038 at 03:14:08 UTC

### ISSUE THREAD

**Issue by nepcore** [meshnet/Documentation#14]
The current master of the N2NP defines broadcasts to have a timestamp for the time the broadcast was issued, this timestamp is defined to be 32 bits (4 bytes) long which will cause the timestamp to overflow on 19th of January 2038 at 03:14:08 UTC

This would cause all new broadcasts to be considered expired from their creation

One way to prevent this would be to double the length of the timestamp to 64 bits (8 bytes)

**Comment by Ne02ptzero** [comment]
Thank you for the feedback.

You are totally right, I think we should increase the timestamp in the packet to 8 bytes.
I'll make a PR if everyone's okay with it.

It is important to note, that we cannot use the `time_t` standard type if we increase the size to 8 bytes, both kernel and userland, without patching Linux / the libc. It might be a problem later, I don't know a userspace stacks (Ex: Node) will react to not standard timestamps.

**Comment by 0x5c** [comment]
@Ne02ptzero What would be the most standard way to implement the timestamp?

**Comment by nepcore** [comment]
As far as i know most up to date systems do consider the timestamp 8 bytes to prevent this issue

I guess they probably just drop the 4 extra bytes for whatever needs the 4 byte version since that is possible for another almost 20 years, just speculation though

**Comment by Ne02ptzero** [comment]
@nepcore Yeah we could do that.
Something like:
```C
typedef struct {
    time_t one;
    time_t two;
} __attribute__((packed)) meshnet_time_t;

...

#ifdef TIME_ENDS_2038
# define time(ptr) ptr.one = time(NULL)
#else
# define time(ptr) ptr = time(NULL)
#endif /* TIME_ENDS_2038 */
```

**Comment by 0x5c** [comment]
Since the protocol is supposed to be exposed only to the node itself, I think it's safe to assume that only "up to date" software will have to deal with it.
