### ISSUE TITLE
The "next node" field was omitted from the N2NP

### ISSUE THREAD

**Issue by 0x5c** [meshnet/Documentation#20]
Since the routing mechanism requires that each node on the path explicitly declares which node will be the next hop, there should be a field for the next hop in the packet header.

Originally reported by Jetse (@JetseVerschuren) on [Slack](https://meshdevice.slack.com/archives/C884ZENJK/p1519213372000204).

**Comment by JetseVerschuren** [comment]
I think that the easiest way to solve it would be to point the header address to the next hop and add a final address to the CHAT service.

**Comment by 0x5c** [comment]
The issue still applies to any packet, not just the `CHAT` service.

**Comment by JetseVerschuren** [comment]
But what other packets need to be routed?

**Comment by 0x5c** [comment]
`PING/PONG`, `CHAT` and any other future service that may require routing

**Comment by JetseVerschuren** [comment]
Isn't the idea of ping and pong to test direct nodes?

**Comment by 0x5c** [comment]
> Isn't the idea of ping and pong to test direct nodes?

It was to test connectivity between two node anywhere in a mesh

**Comment by JetseVerschuren** [comment]
Ok
